#!/usr/bin/env python3
"""mapped.sqlite の business_partners → app スキーマ向け bp_import.sql を生成する.

対象テーブル（すべて冪等 upsert）:
  app.business_partners     — id は mapped の決定的 uuid5 をそのまま使用。
                              match_names = legacy_data.aliases の全表記
                              （AI 抽出の社名照合リスト）。
  app.bp_role_assignments   — CUSTOMER / END_USER / VENDOR（mapped のまま）。
  app.bp_vendor_attrs       — VENDOR ロールの BP に vendor_type='SUPPLIER'
                              （素材発注書由来の仕入先のため）。
  app.numbering_sequences   — BP 通し採番カウンタを取り込み最大値まで前進。

bp_code はレガシー枠 BP-01001〜 を名前順で決定的に割り当てる（デモ/手動作成の
BP-0xxxx 帯と衝突しない）。再実行しても id 衝突→UPDATE となり、bp_code は
初回挿入時のまま保持される。

Usage:  python3 export_bp_import.py [mapped.sqlite] [bp_import.sql]
Apply:  psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f bp_import.sql
"""

import json
import sqlite3
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "mapped.sqlite"
OUT = sys.argv[2] if len(sys.argv) > 2 else "bp_import.sql"

LEGACY_CODE_BASE = 1000  # BP-01001 から


def q(s: str) -> str:
    """SQL string literal (standard_conforming_strings)."""
    return "'" + s.replace("'", "''") + "'"


def text_array(items: list[str]) -> str:
    if not items:
        return "ARRAY[]::TEXT[]"
    return "ARRAY[" + ",".join(q(i) for i in items) + "]::TEXT[]"


def main() -> None:
    db = sqlite3.connect(SRC)
    rows = db.execute(
        "SELECT id, name, legacy_data FROM business_partners ORDER BY id"
    ).fetchall()
    roles = db.execute(
        "SELECT bp_id, role FROM bp_role_assignments ORDER BY bp_id, role"
    ).fetchall()
    db.close()

    partners = []
    for bp_id, name_json, legacy_json in rows:
        name = json.loads(name_json) if name_json else {"ja": "", "en": ""}
        legacy = json.loads(legacy_json) if legacy_json else {}
        display = (name.get("ja") or name.get("en") or "").strip()
        # aliases は使用頻度順に並んでいる。表示名も必ず含める。
        match_names: list[str] = []
        for a in legacy.get("aliases", []):
            n = (a.get("name") or "").strip()
            if n and n not in match_names:
                match_names.append(n)
        if display and display not in match_names:
            match_names.insert(0, display)
        partners.append((bp_id, display, name, match_names))

    # bp_code は表示名（ja）順で決定的に割り当て
    partners.sort(key=lambda p: (p[1], p[0]))
    role_map: dict[str, list[str]] = {}
    for bp_id, role in roles:
        role_map.setdefault(bp_id, []).append(role)

    lines = [
        "-- Generated by export_bp_import.py — legacy FileMaker BPs -> app schema.",
        "-- Idempotent: safe to re-run (id upsert keeps bp_code from first run).",
        "BEGIN;",
    ]
    last_code = LEGACY_CODE_BASE
    for i, (bp_id, display, name, match_names) in enumerate(partners):
        last_code = LEGACY_CODE_BASE + i + 1
        code = f"BP-{last_code:05d}"
        name_lit = q(json.dumps(
            {"ja": name.get("ja", ""), "en": name.get("en", "") or name.get("ja", "")},
            ensure_ascii=False,
        ))
        lines.append(
            "INSERT INTO app.business_partners\n"
            "  (id, bp_code, name, match_names, is_active, created_at, updated_at)\n"
            f"VALUES ('{bp_id}'::uuid, {q(code)}, {name_lit}::jsonb, {text_array(match_names)}, true, now(), now())\n"
            "ON CONFLICT (id) DO UPDATE SET\n"
            "  name = EXCLUDED.name,\n"
            "  match_names = EXCLUDED.match_names,\n"
            "  updated_at = now();"
        )
        for role in sorted(role_map.get(bp_id, [])):
            lines.append(
                "INSERT INTO app.bp_role_assignments (bp_id, role)\n"
                f"VALUES ('{bp_id}'::uuid, {q(role)}::app.\"BP_ROLE\")\n"
                "ON CONFLICT (bp_id, role) DO NOTHING;"
            )
        if "VENDOR" in role_map.get(bp_id, []):
            lines.append(
                "INSERT INTO app.bp_vendor_attrs (bp_id, vendor_type)\n"
                f"VALUES ('{bp_id}'::uuid, 'SUPPLIER'::app.\"VENDOR_TYPE\")\n"
                "ON CONFLICT (bp_id) DO NOTHING;"
            )

    lines.append(
        "INSERT INTO app.numbering_sequences (key, prefix, last_year_month, last_sequence, updated_at)\n"
        f"VALUES ('BP', 'BP', NULL, {last_code}, now())\n"
        "ON CONFLICT (key) DO UPDATE SET\n"
        f"  last_sequence = GREATEST(app.numbering_sequences.last_sequence, {last_code}),\n"
        "  updated_at = now();"
    )
    lines.append("COMMIT;")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n\n".join(lines) + "\n")

    n_roles = sum(len(v) for v in role_map.values())
    n_vendors = sum(1 for v in role_map.values() if "VENDOR" in v)
    print(
        f"{OUT}: {len(partners)} partners "
        f"(codes BP-{LEGACY_CODE_BASE + 1:05d}..BP-{last_code:05d}), "
        f"{n_roles} role assignments, {n_vendors} vendor attrs"
    )


if __name__ == "__main__":
    main()
