#!/usr/bin/env python3
"""mapped.sqlite の material_types / products → app スキーマ向け import SQL を生成する.

出力（すべて冪等 upsert。内部 id は SERIAL — mapped の決定的 uuid5 は
legacy_key に保持し、それを冪等キーにする）:
  material_types_import.sql — 材種プレースホルダ ~3,555 行
                              （レガシー材種はフリーテキストで採番表コードに
                              未変換 = code NULL。name に原文）
  products_import.sql       — 製品 ~43,444 行（型番形状/形状/刃数 由来。
                              spec = {shape, blade_count}、material_id null、
                              コード未採番 = year_month/seq NULL）

materials はレガシーに実体がないため対象外 — 単純パース可能な行の構造化は
export_material_structuring.py（025）が行う。

Usage:  python3 export_master_import.py [mapped.sqlite] [out_dir]
Apply:  psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f <file>
"""

import json
import sqlite3
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "mapped.sqlite"
OUT_DIR = sys.argv[2] if len(sys.argv) > 2 else "."
BATCH = 500

UNMAPPED_DESC = json.dumps(
    {"ja": "レガシー材種（採番表コード未変換）", "en": "Legacy grade (not yet mapped to code table)"},
    ensure_ascii=False,
)


def q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def jname(name_json: str | None) -> str:
    name = json.loads(name_json) if name_json else {"ja": "", "en": ""}
    ja = name.get("ja", "")
    return q(json.dumps({"ja": ja, "en": name.get("en", "") or ja}, ensure_ascii=False))


def write_batched(path: str, header: str, insert_head: str, rows: list[str], conflict: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(header + "\nBEGIN;\n\n")
        for i in range(0, len(rows), BATCH):
            f.write(insert_head + "\n")
            f.write(",\n".join(rows[i : i + BATCH]))
            f.write("\n" + conflict + "\n\n")
        f.write("COMMIT;\n")


def main() -> None:
    db = sqlite3.connect(SRC)

    mt_rows = []
    for mt_id, name_json in db.execute("SELECT id, name FROM material_types ORDER BY id"):
        mt_rows.append(
            f"({q(mt_id)}, {jname(name_json)}::jsonb, {q(UNMAPPED_DESC)}::jsonb, true, now(), now())"
        )
    write_batched(
        f"{OUT_DIR}/material_types_import.sql",
        "-- Generated by export_master_import.py — legacy 材種 placeholders.\n"
        "-- Idempotent: legacy_key upsert refreshes name/description (id は SERIAL).",
        "INSERT INTO app.material_types (legacy_key, name, description, is_active, created_at, updated_at) VALUES",
        mt_rows,
        "ON CONFLICT (legacy_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, updated_at = now();",
    )

    prod_rows = []
    for pid, name_json, unit, spec_json in db.execute(
        "SELECT id, name, unit, spec FROM products ORDER BY id"
    ):
        spec = f"{q(spec_json)}::jsonb" if spec_json else "NULL"
        prod_rows.append(
            f"({q(pid)}, {jname(name_json)}::jsonb, {q(unit or '本')}, {spec}, true, now(), now())"
        )
    write_batched(
        f"{OUT_DIR}/products_import.sql",
        "-- Generated by export_master_import.py — legacy 製品 (型番形状/形状/刃数).\n"
        "-- Idempotent: legacy_key upsert refreshes name/spec（id は SERIAL、コード未採番）.",
        "INSERT INTO app.products (legacy_key, name, unit, spec, is_active, created_at, updated_at) VALUES",
        prod_rows,
        "ON CONFLICT (legacy_key) DO UPDATE SET name = EXCLUDED.name, spec = EXCLUDED.spec, updated_at = now();",
    )

    db.close()
    print(f"material_types_import.sql: {len(mt_rows)} rows")
    print(f"products_import.sql: {len(prod_rows)} rows")


if __name__ == "__main__":
    main()
