#!/usr/bin/env bash
# dev-local.sh — start (or restart) nextjs-web locally with hot reload.
#
# One command: ./scripts/dev-local.sh   (re-run it to restart cleanly)
#              ./scripts/dev-local.sh stop   (tear down tunnel + dev server)
#
# The dev DB (shared-db/ckk on 192.168.50.15) publishes no host port — it is
# only reachable inside Docker on the server. So this script opens an SSH tunnel
# (127.0.0.1:<port> -> shared-db container:5432), writes a gitignored .env.local
# pointing DATABASE_URL at that tunnel, then runs `pnpm dev` (Turbopack hot
# reload). Your local writes hit the shared DEV database.
#
# Env overrides: DB_SSH_HOST (192.168.50.15), DB_CONTAINER (shared-db),
#                DB_TUNNEL_PORT (25432), PORT (3000).
set -euo pipefail

SERVER="${DB_SSH_HOST:-192.168.50.15}"
CONTAINER="${DB_CONTAINER:-shared-db}"
LOCAL_PORT="${DB_TUNNEL_PORT:-25432}"
APP_PORT="${PORT:-3000}"

cd "$(dirname "$0")/.."   # nextjs-web root
ROOT="$(pwd)"
SHARED_ENV="$ROOT/../../shared-db/.env"
ENV_LOCAL="$ROOT/.env.local"

log() { printf '\033[1;36m[dev-local]\033[0m %s\n' "$*"; }

kill_port() {
  # Kill whatever is listening on the given TCP port (tunnel / dev server).
  lsof -ti "tcp:$1" 2>/dev/null | xargs -r kill 2>/dev/null || true
}

# Re-running == restart: always tear down the old tunnel + dev server first.
log "stopping existing tunnel (:$LOCAL_PORT) and dev server (:$APP_PORT)"
kill_port "$LOCAL_PORT"
kill_port "$APP_PORT"

if [ "${1:-}" = "stop" ]; then
  log "stopped."
  exit 0
fi

[ -f "$SHARED_ENV" ] || {
  echo "dev-local: shared-db/.env not found at $SHARED_ENV" >&2
  exit 1
}

# 1. Resolve the shared-db container's Docker IP (reachable from the server host).
log "resolving $CONTAINER IP on $SERVER"
CIP="$(ssh -o ConnectTimeout=10 "$SERVER" \
  "docker inspect $CONTAINER --format '{{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}'" \
  | awk '{print $1}')"
[ -n "$CIP" ] || {
  echo "dev-local: could not resolve $CONTAINER IP on $SERVER" >&2
  exit 1
}

# 2. Open the SSH tunnel in the background (keepalive so it survives idle time).
log "opening tunnel 127.0.0.1:$LOCAL_PORT -> $CONTAINER($CIP):5432"
ssh -f -N \
  -o ServerAliveInterval=30 -o ServerAliveCountMax=3 \
  -o ExitOnForwardFailure=yes \
  -L "$LOCAL_PORT:$CIP:5432" "$SERVER"

# 3. Derive the tunneled DATABASE_URL from shared-db/.env (swap host:port only).
SRC_URL="$(grep -E '^DATABASE_URL=' "$SHARED_ENV" | head -1 | sed -E 's/^DATABASE_URL=//; s/^"//; s/"$//')"
[ -n "$SRC_URL" ] || {
  echo "dev-local: DATABASE_URL missing in $SHARED_ENV" >&2
  exit 1
}
DB_URL="$(printf '%s' "$SRC_URL" | sed -E "s#@[^/]+/#@127.0.0.1:$LOCAL_PORT/#")"

# 4. Write .env.local (gitignored). Generate AUTH_SECRET once, then reuse it so
#    existing local sessions survive restarts.
if [ -f "$ENV_LOCAL" ] && grep -q '^AUTH_SECRET=' "$ENV_LOCAL"; then
  AUTH_SECRET="$(grep -E '^AUTH_SECRET=' "$ENV_LOCAL" | head -1 | sed -E 's/^AUTH_SECRET=//')"
else
  AUTH_SECRET="$(openssl rand -base64 32)"
fi
cat > "$ENV_LOCAL" <<EOF
# Generated by scripts/dev-local.sh — LOCAL DEV ONLY (gitignored). Do not commit.
NEXT_PUBLIC_APP_VERSION=0.1.0-local
APP_ENV=dev
AUTH_URL=http://localhost:$APP_PORT
AUTH_SECRET=$AUTH_SECRET
DATABASE_URL=$DB_URL
EOF
log "wrote $ENV_LOCAL (DATABASE_URL -> shared dev DB via tunnel)"

# 5. Ensure the generated Prisma client exists (schema is a synced copy).
if [ ! -d "$ROOT/generated/client" ]; then
  log "generating Prisma client (pnpm db:generate)"
  pnpm db:generate
fi

# 6. Start Next.js dev with hot reload. `exec` so Ctrl-C stops the server.
export PORT="$APP_PORT"
log "starting Next.js dev (hot reload) on http://localhost:$APP_PORT"
log "(re-run this script to restart · './scripts/dev-local.sh stop' to tear down)"
exec pnpm dev
