-- directory-bootstrap.sql — ldap_sync 所有テーブルの最小ブートストラップ。
--
-- directory.employee_directory は vpn-ldap の ldap-sync サービスが作る前提で、
-- Prisma migration は ALTER（ldap_guid 追加等）しかしない。そのため
-- 「まっさらなローカル DB に migrate deploy」する場合（tools/docs-screenshots
-- の一時 DB など）は、先にこのファイルで土台を作る必要がある。冪等。
-- 本番/dev には適用不要（実テーブルは ldap-sync が管理）。

CREATE SCHEMA IF NOT EXISTS directory;

CREATE TABLE IF NOT EXISTS directory.employee_directory (
  username        text PRIMARY KEY,
  display_name    text,
  email           text,
  department      text,
  title           text,
  company         text,
  office          text,
  manager         text,
  is_active       boolean,
  employee_code   integer,
  member_of       text[] NOT NULL DEFAULT '{}',
  last_synced_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS directory.ldap_sync_log (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  finished_at  timestamptz NOT NULL DEFAULT now(),
  kind         text,
  status       text,
  total        int,
  message      text
);
CREATE INDEX IF NOT EXISTS idx_ldap_sync_log_finished
  ON directory.ldap_sync_log (finished_at DESC);
