-- Baseline 1/6 — schemas, extensions, enum types.
-- Squashed from the 99-migration history (2026-08-24). See shared-db/README.md.

-- app (SCHEMA)
CREATE SCHEMA app;

-- directory (SCHEMA)
CREATE SCHEMA directory;

-- PGroonga は本番 DB のみ（開発ホストでは未導入のことがある）。
DO $$
BEGIN
  CREATE EXTENSION IF NOT EXISTS pgroonga;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'pgroonga unavailable on this host — skipped';
END
$$;

-- app.ACTION (TYPE)
CREATE TYPE app."ACTION" AS ENUM (
    'READ',
    'CREATE',
    'UPDATE',
    'DELETE',
    'EXPORT',
    'APPROVE',
    'ADMIN'
);

-- app.APPROVAL_ACTION (TYPE)
CREATE TYPE app."APPROVAL_ACTION" AS ENUM (
    'APPROVED',
    'REJECTED'
);

-- app.APPROVAL_MODE (TYPE)
CREATE TYPE app."APPROVAL_MODE" AS ENUM (
    'ANY',
    'ALL'
);

-- app.APPROVAL_REQUEST_STATUS (TYPE)
CREATE TYPE app."APPROVAL_REQUEST_STATUS" AS ENUM (
    'PENDING',
    'APPROVED',
    'REJECTED'
);

-- app.BP_ROLE (TYPE)
CREATE TYPE app."BP_ROLE" AS ENUM (
    'CUSTOMER',
    'VENDOR',
    'END_USER'
);

-- app.BRANCH_STOCK_DISPOSITION (TYPE)
CREATE TYPE app."BRANCH_STOCK_DISPOSITION" AS ENUM (
    'SEMI_FINISHED',
    'PRODUCT'
);

-- app.CLOSING_STATUS (TYPE)
CREATE TYPE app."CLOSING_STATUS" AS ENUM (
    'PENDING',
    'PROCESSED',
    'EXPORTED'
);

-- app.DELIVERY_METHOD (TYPE)
CREATE TYPE app."DELIVERY_METHOD" AS ENUM (
    'DIRECT_TO_USER',
    'NORMAL'
);

-- app.DELIVERY_ORDER_STATUS (TYPE)
CREATE TYPE app."DELIVERY_ORDER_STATUS" AS ENUM (
    'DRAFT',
    'CONFIRMED',
    'SHIPPED'
);

-- app.DELIVERY_ORDER_TYPE (TYPE)
CREATE TYPE app."DELIVERY_ORDER_TYPE" AS ENUM (
    'STOCK_STORAGE',
    'DISPATCH'
);

-- app.DELIVERY_STATUS (TYPE)
CREATE TYPE app."DELIVERY_STATUS" AS ENUM (
    'DRAFT',
    'ISSUED',
    'DELIVERED'
);

-- app.DEPENDENCY_RELATION (TYPE)
CREATE TYPE app."DEPENDENCY_RELATION" AS ENUM (
    'AND',
    'OR'
);

-- app.DESIGN_STATUS (TYPE)
CREATE TYPE app."DESIGN_STATUS" AS ENUM (
    'PENDING',
    'IN_PROGRESS',
    'COMPLETED'
);

-- app.DESIGN_TRIGGER (TYPE)
CREATE TYPE app."DESIGN_TRIGGER" AS ENUM (
    'QUOTE',
    'SALES_ORDER'
);

-- app.ESTIMATE_STATUS (TYPE)
CREATE TYPE app."ESTIMATE_STATUS" AS ENUM (
    'DRAFT',
    'CONFIRMED',
    'REGISTERED'
);

-- app.INSPECTION_STATUS (TYPE)
CREATE TYPE app."INSPECTION_STATUS" AS ENUM (
    'PENDING',
    'PASS',
    'FAIL',
    'APPROVED'
);

-- app.INTAKE_SOURCE (TYPE)
CREATE TYPE app."INTAKE_SOURCE" AS ENUM (
    'FOLDER',
    'UPLOAD',
    'MANUAL'
);

-- app.INVENTORY_TYPE (TYPE)
CREATE TYPE app."INVENTORY_TYPE" AS ENUM (
    'PRODUCT',
    'MATERIAL'
);

-- app.INVOICE_METHOD (TYPE)
CREATE TYPE app."INVOICE_METHOD" AS ENUM (
    'EMAIL',
    'FAX',
    'POST',
    'PORTAL'
);

-- app.INVOICE_STATUS (TYPE)
CREATE TYPE app."INVOICE_STATUS" AS ENUM (
    'DRAFT',
    'ISSUED',
    'SENT',
    'PAID'
);

-- app.InspectionItemType (TYPE)
CREATE TYPE app."InspectionItemType" AS ENUM (
    'BOOLEAN',
    'NUMBER',
    'SELECT_SINGLE',
    'SELECT_MULTI'
);

-- app.InspectionRecordStyle (TYPE)
CREATE TYPE app."InspectionRecordStyle" AS ENUM (
    'VALUES',
    'COUNTS'
);

-- app.InspectionSamplingMode (TYPE)
CREATE TYPE app."InspectionSamplingMode" AS ENUM (
    'ALL',
    'PERCENT',
    'COUNT'
);

-- app.KIOSK_CARD_STATUS (TYPE)
CREATE TYPE app."KIOSK_CARD_STATUS" AS ENUM (
    'UNASSIGNED',
    'ASSIGNED',
    'SUSPENDED',
    'REVOKED'
);

-- app.KIOSK_DEVICE_LOG_TYPE (TYPE)
CREATE TYPE app."KIOSK_DEVICE_LOG_TYPE" AS ENUM (
    'ONLINE',
    'OFFLINE',
    'LOGIN',
    'LOGOUT'
);

-- app.KIOSK_DEVICE_STATUS (TYPE)
CREATE TYPE app."KIOSK_DEVICE_STATUS" AS ENUM (
    'PENDING',
    'ACTIVE',
    'DISABLED',
    'REVOKED',
    'LINKED'
);

-- app.LOT_INPUT_MODE (TYPE)
CREATE TYPE app."LOT_INPUT_MODE" AS ENUM (
    'REQUIRED',
    'OPTIONAL',
    'NONE'
);

-- app.ORDER_ACCEPTANCE_STATUS (TYPE)
CREATE TYPE app."ORDER_ACCEPTANCE_STATUS" AS ENUM (
    'IMPORT',
    'DRAFT',
    'REQUESTED',
    'APPROVED',
    'COMPLETED',
    'ARCHIVED',
    'CANCELLED'
);

-- app.ORDER_LINE_STATUS (TYPE)
CREATE TYPE app."ORDER_LINE_STATUS" AS ENUM (
    'DRAFT',
    'CONFIRMED',
    'IN_PRODUCTION',
    'PARTIAL_SHIPPED',
    'SHIPPED',
    'CANCELLED'
);

-- app.ORDER_TYPE (TYPE)
CREATE TYPE app."ORDER_TYPE" AS ENUM (
    'PRODUCTION',
    'TEST',
    'SAMPLE',
    'OTHER'
);

-- app.PRICE_DISCOUNT_TYPE (TYPE)
CREATE TYPE app."PRICE_DISCOUNT_TYPE" AS ENUM (
    'RATE',
    'AMOUNT'
);

-- app.PROCESS_CATEGORY (TYPE)
CREATE TYPE app."PROCESS_CATEGORY" AS ENUM (
    'MATERIAL_PREP',
    'MACHINING',
    'COATING',
    'INSPECTION',
    'APPROVAL',
    'SHIPPING'
);

-- app.PROCESS_EXECUTION (TYPE)
CREATE TYPE app."PROCESS_EXECUTION" AS ENUM (
    'INTERNAL',
    'INTERNAL_OR_OUTSOURCE'
);

-- app.PURCHASE_REQUEST_STATUS (TYPE)
CREATE TYPE app."PURCHASE_REQUEST_STATUS" AS ENUM (
    'DRAFT',
    'REQUESTED',
    'APPROVED',
    'REJECTED',
    'ORDERED',
    'CANCELLED'
);

-- app.PURCHASE_STATUS (TYPE)
CREATE TYPE app."PURCHASE_STATUS" AS ENUM (
    'DRAFT',
    'REQUESTED',
    'APPROVED',
    'ORDERED',
    'COMPLETED',
    'CANCELLED'
);

-- app.QUANTITY_TRACKING (TYPE)
CREATE TYPE app."QUANTITY_TRACKING" AS ENUM (
    'NONE',
    'FLOW',
    'INSPECTION'
);

-- app.QUOTE_STATUS (TYPE)
CREATE TYPE app."QUOTE_STATUS" AS ENUM (
    'DRAFT',
    'ISSUED',
    'ACCEPTED',
    'REJECTED',
    'EXPIRED'
);

-- app.RESERVATION_STATUS (TYPE)
CREATE TYPE app."RESERVATION_STATUS" AS ENUM (
    'RESERVED',
    'CONFIRMED',
    'RELEASED'
);

-- app.SCOPE (TYPE)
CREATE TYPE app."SCOPE" AS ENUM (
    'ALL',
    'REGION',
    'COUNTRY',
    'PLANT',
    'DEPARTMENT',
    'TEAM',
    'SUB',
    'OWN'
);

-- app.STEP_EXECUTION (TYPE)
CREATE TYPE app."STEP_EXECUTION" AS ENUM (
    'INTERNAL',
    'OUTSOURCE'
);

-- app.STEP_STATUS (TYPE)
CREATE TYPE app."STEP_STATUS" AS ENUM (
    'PENDING',
    'IN_PROGRESS',
    'COMPLETED',
    'CANCELLED'
);

-- app.TAX_TYPE (TYPE)
CREATE TYPE app."TAX_TYPE" AS ENUM (
    'TAXABLE',
    'EXEMPT',
    'REDUCED'
);

-- app.TRANSACTION_TYPE (TYPE)
CREATE TYPE app."TRANSACTION_TYPE" AS ENUM (
    'IN',
    'OUT',
    'RESERVE',
    'RELEASE',
    'ADJUST'
);

-- app.USER_GROUP (TYPE)
CREATE TYPE app."USER_GROUP" AS ENUM (
    'SYSTEM',
    'EMPLOYEE',
    'GUEST'
);

-- app.VENDOR_TYPE (TYPE)
CREATE TYPE app."VENDOR_TYPE" AS ENUM (
    'SUPPLIER',
    'OUTSOURCE'
);

-- app.WORK_ORDER_APPROVAL_STATUS (TYPE)
CREATE TYPE app."WORK_ORDER_APPROVAL_STATUS" AS ENUM (
    'NONE',
    'PENDING',
    'APPROVED',
    'REJECTED'
);

-- app.WORK_ORDER_STATUS (TYPE)
CREATE TYPE app."WORK_ORDER_STATUS" AS ENUM (
    'DRAFT',
    'PENDING_APPROVAL',
    'APPROVED',
    'IN_PROGRESS',
    'COMPLETED',
    'CANCELLED'
);

-- app.WORK_ORDER_TYPE (TYPE)
CREATE TYPE app."WORK_ORDER_TYPE" AS ENUM (
    'FROM_STOCK',
    'MANUFACTURE'
);
